# filepath: app/backend_engine.py
import asyncio
import logging
from google.adk.runners import InMemoryRunner
from google.genai import types
from app.root_gateway import root_agent

import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="google.adk")

logger = logging.getLogger(__name__)

# Single persistent server-side instance of the ADK runner context
_GLOBAL_RUNNER = None

def get_backend_runner():
    """Natively constructs and maintains the server-side ADK execution engine."""
    global _GLOBAL_RUNNER
    if _GLOBAL_RUNNER is None:
        runner = InMemoryRunner(
            agent=root_agent,
            app_name="nexusmind"
        )
        if hasattr(runner, "auto_create_session"):
            runner.auto_create_session = True
        _GLOBAL_RUNNER = runner
    return _GLOBAL_RUNNER

async def execute_nexus_engine(user_id: str, session_id: str, raw_input: str) -> str:
    """Backend service worker executing agents and compiling responses via native ADK utilities."""
    runner = get_backend_runner()
    
    # Explicitly ensure the internal session mapping database is allocated
    service = getattr(runner, "session_service", None)
    if service:
        try:
            if asyncio.iscoroutinefunction(service.create_session):
                await service.create_session(user_id=user_id, session_id=session_id)
            else:
                service.create_session(user_id=user_id, session_id=session_id)
        except Exception:
            pass

    # Fire the async topology stream
    outcome_stream = runner.run_async(
        user_id=user_id,
        session_id=session_id,
        new_message=types.Content(
            role="user",
            parts=[types.Part.from_text(text=raw_input)]
        )
    )

    # -----------------------------------------------------------------
    # 🧠 THE INBUILT ADK AUTO-EXTRACTION WAY
    # -----------------------------------------------------------------
    # Instead of manual nested object checking loops, we let the runner consume 
    # the stream. The framework's internal session manager compiles the events
    # and populates the history. We can natively query the finalized message text!
    
    text_accumulator = ""
    async for event in outcome_stream:
        # Step through the stream to allow the graph execution to complete natively
        # The ADK uses these iterations to safely route across nodes and tool sets
        if hasattr(event, "author") and event.author == "SystemRootGateway":
            continue
        
        # Pull text from content updates automatically using the standard ADK model interface
        if hasattr(event, "content") and event.content:
            c = event.content
            if hasattr(c, "parts") and c.parts:
                for part in c.parts:
                    if hasattr(part, "text") and part.text:
                        text_accumulator += part.text

    final_text = text_accumulator.strip()
    return final_text if final_text else "No response generated by the cognitive topology."