# filepath: app/backend_engine.py
import uuid
import asyncio
import logging
from pathlib import Path
from google.adk.runners import InMemoryRunner
from google.genai import types

from app.root_gateway import root_agent
from app.ingest_pipeline import ingest_workflow_pipeline
from app.infrastructure import pdf_extractor

import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="google.adk")

logger = logging.getLogger(__name__)

# Path mappings to look into your local data/ repository
PROJECT_ROOT = Path(__file__).parent.parent.resolve()
DATA_DIR = PROJECT_ROOT / "data"

# Single persistent server-side instance of the ADK runner context
_GLOBAL_RUNNER = None

def get_backend_runner():
    """Natively constructs and maintains the server-side ADK execution engine."""
    global _GLOBAL_RUNNER
    if _GLOBAL_RUNNER is None:
        runner = InMemoryRunner(
            agent=root_agent,
            app_name="nexusmind"
        )
        if hasattr(runner, "auto_create_session"):
            runner.auto_create_session = True
        _GLOBAL_RUNNER = runner
    return _GLOBAL_RUNNER

async def execute_nexus_engine(user_id: str, session_id: str, raw_input: str) -> str:
    """Backend service worker executing agents and compiling responses via native ADK utilities."""
    runner = get_backend_runner()
    
    # Explicitly ensure the internal session mapping database is allocated
    service = getattr(runner, "session_service", None)
    if service:
        try:
            if asyncio.iscoroutinefunction(service.create_session):
                await service.create_session(user_id=user_id, session_id=session_id)
            else:
                service.create_session(user_id=user_id, session_id=session_id)
        except Exception:
            pass

    # Fire the async topology stream
    outcome_stream = runner.run_async(
        user_id=user_id,
        session_id=session_id,
        new_message=types.Content(
            role="user",
            parts=[types.Part.from_text(text=raw_input)]
        )
    )

    # -----------------------------------------------------------------
    # 🧠 THE INBUILT ADK AUTO-EXTRACTION WAY
    # -----------------------------------------------------------------
    text_accumulator = ""
    async for event in outcome_stream:
        # Step through the stream to allow the graph execution to complete natively
        if hasattr(event, "author") and event.author == "SystemRootGateway":
            continue
        
        # Pull text from content updates automatically using the standard ADK model interface
        if hasattr(event, "content") and event.content:
            c = event.content
            if hasattr(c, "parts") and c.parts:
                for part in c.parts:
                    if hasattr(part, "text") and part.text:
                        text_accumulator += part.text

    final_text = text_accumulator.strip()
    return final_text if final_text else "No response generated by the cognitive topology."


# =====================================================================
# 📁 DIRECT FILE INGESTION SERVICE WORKER
# =====================================================================

async def process_file_ingestion(file_name: str) -> str:
    """
    Reads a file stored locally inside the data/ folder, parses layout content, 
    and drives the ingest workflow pipeline directly—completely bypassing the conversation logic.
    """
    file_path = DATA_DIR / file_name
    if not file_path.exists():
        return f"Error: File '{file_name}' resource target missing inside data folder configuration."

    # Parse raw bytes out of the specified data directory asset path
    with open(file_path, "rb") as f:
        raw_bytes = f.read()
    
    # Extract clean semantic layout dumps using your local utility module
    parsed_text_dump = pdf_extractor.extract_clean_text(raw_bytes)
    payload_string = f"DOCUMENT_INJECT_STREAM:\nFilename: {file_name}\nContent:\n{parsed_text_dump}"

    # Spin up an isolated batch runner for the ingestion pipeline topology
    runner = InMemoryRunner(
        agent=ingest_workflow_pipeline, 
        app_name="nexusmind_batch_ingest"
    )
    if hasattr(runner, "auto_create_session"):
        runner.auto_create_session = True

    isolated_session = f"ingest_{uuid.uuid4().hex[:8]}"
    
    service = getattr(runner, "session_service", None)
    if service:
        try:
            if asyncio.iscoroutinefunction(service.create_session):
                await service.create_session(user_id="ingest_service", session_id=isolated_session)
            else:
                service.create_session(user_id="ingest_service", session_id=isolated_session)
        except Exception:
            pass

    outcome_stream = runner.run_async(
        user_id="ingest_service",
        session_id=isolated_session,
        new_message=types.Content(
            role="user",
            parts=[types.Part.from_text(text=payload_string)]
        )
    )

    text_accumulator = ""
    async for event in outcome_stream:
        if hasattr(event, "text") and event.text:
            text_accumulator += event.text
        elif hasattr(event, "content") and event.content:
            c = event.content
            if hasattr(c, "parts"):
                for part in c.parts:
                    if hasattr(part, "text") and part.text:
                        text_accumulator += part.text

    return text_accumulator.strip()