# filepath: app/ingest_pipeline.py
import logging
import json
import uuid
from typing import Dict, Any, List
from google.genai import types
from google.adk import Agent, Workflow
from google.adk.runners import InMemoryRunner
from google.adk.models.lite_llm import LiteLlm
from google.adk.workflow import START, node
from pydantic import BaseModel, Field
from config.settings import settings

from app.services import pdf_processor, vector_store, graph_db

logger = logging.getLogger(__name__)
ingestion_llm = LiteLlm(model=settings.OLLAMA_MODEL)

# =========================================================
# 1. STRUCTURAL PIPELINE STATE SCHEMA
# =========================================================
class IngestionState(BaseModel):
    chunk_id: str = Field(default="", description="The unique persistent identifier allocated to the text fragment.")
    chunk_text: str = Field(default="", description="The raw linguistic slice content to perform mining extraction against.")
    extracted_entities_raw: str = Field(default="", description="The temporary raw unstructured JSON concept token array string.")

# =========================================================
# 2. REFINED MINING AGENTS
# =========================================================

entity_extractor_agent = Agent(
    name="EntityExtractorAgent",
    description="Mines precise technical abstractions and concepts from targeted document chunks.",
    model=ingestion_llm,
    instruction="""
    TASK: Extract domain concepts and technical architectures from the provided text: {chunk_text}.
    Categorize entries explicitly into one of these types: Concept, Technology, System.
    
    OUTPUT FORMAT: You must return a strict, valid JSON object matching this schema:
    {"entities": [{"name": "Concept Name", "type": "Type"}]}
    
    CRITICAL: Output ONLY valid raw JSON. Do not write markdown wrappers, triple backticks, or introduction text.
    """,
    output_key="extracted_entities_raw"
)

indexer_agent = Agent(
    name="IndexerAgent",
    description="Synchronized storage worker calling system functions to register conceptual graph edges.",
    model=ingestion_llm,
    instruction="""
    ROLE: Data Sync Coordinator.
    TASK: Read the validated incoming extraction payload and link it directly with the reference identifier: {chunk_id}.
    
    EXECUTION SEQUENCE:
    For every mined element object found in your data input, invoke your `save_concept_mention` tool 
    to create a persistent relationship between that term node and the chunk ID.
    """,
    tools=[graph_db.save_concept_mention]
)

# =========================================================
# 3. INTERMEDIATE HOOK / DATA TRANSFORMATION NODE
# =========================================================
@node
def clean_and_parse_extraction(ctx: Workflow, node_input: Any) -> Any:
    """
    🌟 THE CONTEXT BRIDGE:
    Cleans up any conversational text or backticks left over by local 7B models, 
    parses the JSON safely, and cleanly passes the list payload to the indexer agent.
    """
    raw_payload = ctx.state.get("extracted_entities_raw", "").strip()
    
    # Strip any potential markdown code blocks generated by smaller LLMs
    if raw_payload.startswith("```"):
        raw_payload = raw_payload.split("\n", 1)[-1].rsplit("```", 1)[0].strip()
    if raw_payload.upper().startswith("JSON"):
        raw_payload = raw_payload[4:].strip()

    try:
        parsed_data = json.loads(raw_payload)
        entities = parsed_data.get("entities", [])
        logger.info(f"💾 Cleaned extraction pass. Found {len(entities)} concept edges for ID: {ctx.state.get('chunk_id')}")
        return entities
    except Exception as e:
        logger.error(f"⚠️ Failed JSON normalization block pass. Error: {str(e)} | Raw: {raw_payload}")
        return []

# =========================================================
# 4. WORKFLOW TOPOLOGY DEFINITION
# =========================================================
ingest_workflow_pipeline = Workflow(
    name="IngestionPipeline",
    state_schema=IngestionState,
    edges=[
        (START, entity_extractor_agent),
        (entity_extractor_agent, clean_and_parse_extraction),
        (clean_and_parse_extraction, indexer_agent)
    ]
)

# =========================================================
# 5. EXECUTION ENGINE FLOW MANAGER
# =========================================================
class NexusIngestionFlowEngine:
    @staticmethod
    async def ingest_pdf_document(file_content_stream: str, filename: str) -> Dict[str, Any]:
        logger.info(f"📁 Running ingestion graph for file: '{filename}'")
        print(f"\n🚀 Commencing layout parsing graph layer for target asset: '{filename}'")
        
        try:
            hierarchical_chunks = pdf_processor.slice_hierarchical_chunks(
                text=file_content_stream,
                document_name=filename
            )
            
            pipeline_runner = InMemoryRunner(agent=ingest_workflow_pipeline, app_name="app")
            if hasattr(pipeline_runner, "auto_create_session"):
                pipeline_runner.auto_create_session = True
                
            report_accumulator = []
            
            for block in hierarchical_chunks:
                p_id = block["parent_id"]
                p_text = block["parent_text"]
                child_fragments = block["children"]
                
                print(f"\n📦 Analyzing Parent Segment Block [ {p_id} ]")
                
                for child in child_fragments:
                    c_id = child["id"]
                    c_text = child["text"]
                    
                    print(f"📡 Processing [ {c_id} ] ➔ Vector Store & Graph Node Assembly...")
                    
                    # ✅ LAYER 1: Core Database Writes happen deterministically via safe Python calls
                    vector_store.insert_child_vector(child_id=c_id, child_text=c_text, parent_id=p_id)
                    graph_db.save_hierarchical_edge(child_id=c_id, parent_id=p_id, parent_text=p_text)
                    
                    # ✅ LAYER 2: Multi-Agent Pipeline leverages structured scratchpad context
                    isolated_session = f"block_{c_id.replace('-', '_')}_{uuid.uuid4().hex[:4]}"
                    
                    # Pre-prime the runner session context dictionary state explicitly
                    initial_context_scratchpad = {
                        "chunk_id": c_id,
                        "chunk_text": c_text
                    }
                    
                    outcome_stream = pipeline_runner.run_async(
                        user_id="ingest_cli_service",
                        session_id=isolated_session,
                        state=initial_context_scratchpad, # Injects variables directly into ctx
                        new_message=types.Content(
                            role="user",
                            parts=[types.Part.from_text(text="Commence knowledge mining sequence.")]
                        )
                    )

                    text_accumulator = ""
                    async for event in outcome_stream:
                        if hasattr(event, "text") and event.text:
                            text_accumulator += event.text
                        elif hasattr(event, "content") and event.content:
                            c = event.content
                            if hasattr(c, "parts"):
                                for part in c.parts:
                                    if hasattr(part, "text") and part.text:
                                        text_accumulator += part.text
                                        
                    report_accumulator.append(text_accumulator.strip())

            print("\n🏁 All parent/child workflow blocks synthesized safely.")
            unified_report = "\n\n".join([r for r in report_accumulator if r])
            return {
                "status": "SUCCESS",
                "markdown_answer": f"### 📁 Processing Report: PDF Ingestion Success\n\n{unified_report}"
            }
            
        except Exception as e:
            print(f"\n❌ Thread collapsed: {str(e)}")
            logger.error(f"❌ Ingestion crashed: {str(e)}")
            return {
                "status": "CRASHED",
                "markdown_answer": f"❌ **Ingestion failure tracker dump:** {str(e)}"
            }

ingest_flow_engine = NexusIngestionFlowEngine()