# filepath: scripts/ingest.py
import os
import sys
import argparse
import asyncio
import shutil
from pathlib import Path

# Connect directly to our finalized architecture's engine
from app.ingest_pipeline import ingest_flow_engine
from app.infrastructure import pdf_extractor

# Set up the clean landing path for files destined for ingestion
PROJECT_ROOT = Path(__file__).parent.parent.resolve()
DATA_DIR = PROJECT_ROOT / "data"

def setup_ingest_directory():
    """Natively constructs the local ingestion file directory if missing."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    return DATA_DIR

async def run_cli_ingestion(file_path: str):
    target_path = Path(file_path)
    if not target_path.exists() or not target_path.is_file():
        print(f"❌ Error: Target file configuration resource not found: {file_path}")
        sys.exit(1)
        
    if target_path.suffix.lower() != ".pdf":
        print(f"❌ Error: Ingestion architecture strictly enforces standard .pdf validation constraints.")
        sys.exit(1)

    ingest_home = setup_ingest_directory()
    staged_destination = ingest_home / target_path.name
    
    if target_path.parent.resolve() != ingest_home.resolve():
        print(f"📁 Staging a copy into the ingestion channel: {staged_destination}")
        shutil.copy2(target_path, staged_destination)
    else:
        print(f"📁 Processing file directly inside ingestion channel: {staged_destination}")

    print(f"⚙️ Triggering background workflow engine on data/{target_path.name}...")
    try:
        with open(staged_destination, "rb") as f:
            raw_bytes = f.read()
            
        # 1. Extract the clean text stream from the byte buffer
        parsed_text_dump = pdf_extractor.extract_clean_text(raw_bytes)

        # ⚡ FIX: Pass the pure extracted text directly to the engine wrapper.
        # The engine will wrap this context cleanly within its internal programmatic parent blocks.
        report_output = await ingest_flow_engine.ingest_pdf_document(
            file_content_stream=parsed_text_dump, 
            filename=target_path.name
        )
        
        print("\n========================================================")
        print("✅ INGESTION PIPELINE EXECUTED SUCCESSFULLY")
        print("========================================================\n")
        print(report_output.get("markdown_answer", "No log summary generated by pipeline."))
        
    except Exception as ex:
        print(f"❌ Operational failure during processing phase: {str(ex)}")
        sys.exit(1)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="NexusMind CLI Document Engine Ingestion Tool")
    parser.add_argument("file", help="Path to the local source PDF document asset")
    args = parser.parse_args()

    asyncio.run(run_cli_ingestion(args.file))